### ISSUE TITLE
Command 'bun create hono my-app' does not work

### ISSUE THREAD

**Issue by ralcorta** [honojs/website#116]
In the documentation it says that I should use the following command to initialize a project:

`$ bun create hono my-app`

But it shows me an error:
![Screenshot 2023-10-05 at 10 51 03](https://github.com/honojs/website/assets/19806540/001afe5d-9155-4524-851a-cbb87295bbb7)

Is there something to fix?

**Comment by NicoPlyley** [comment]
Connection refused seems like it would be a network error, maybe on your end or something with npm registry. You can also try `bunx create-hono my app` and see if that works. If you you can open an issue on the create-hono repo

**Comment by ralcorta** [comment]
@NicoPlyley Yep, I changed my wifi connection and it works fine! Something to take in mind is that npm worked well when bun cli didn't.
