### ISSUE TITLE
HTML middleware docs

### ISSUE THREAD

**Issue by fedgrant** [honojs/website#128]
Hey the docs from this link https://hono.dev/guides/jsx are returning a 404 

<img width="668" alt="Screen Shot 2023-10-18 at 2 24 30 PM" src="https://github.com/honojs/website/assets/2390855/9588f93f-dd08-4035-acd1-f3a96bf1bf3c">

https://hono.dev/middleware/builtin/html

**Comment by yusukebe** [comment]
Hi @fedgrant 

Thanks, fixed it!
