### ISSUE TITLE
Documentation Enhancements

### ISSUE THREAD

**Issue by sor4chi** [honojs/website#147]
List of sections we are planning to add

- [ ] Snippets (Like Bun Document)
  - [ ] file upload #72 
  - [ ]  using OpenAPI
    - [ ] with Swagger UI
  - [ ] create middlewares
- [x] Best practices

**Comment by yusukebe** [comment]
Hi @sor4chi,

Do you have other "snippet" ideas? For example: "using OpenAPI," "routing for serving static files," "writing custom middleware," etc. If you do, please list all of them so we can categorize them.

**Comment by sor4chi** [comment]
Alright.

BTW is the best way to create middleware now is to use `createMiddleware`?

**Comment by yusukebe** [comment]
Yes.

**Comment by sor4chi** [comment]
Cool 👍

**Comment by yusukebe** [comment]
This PR #148 (already merged).

**Comment by sor4chi** [comment]
I've converted the list to Todo.

**Comment by yusukebe** [comment]
We must ensure they do not duplicate the content of the Guides or API pages.

**Comment by yusukebe** [comment]
I think this is good.

<img width="1073" alt="Screenshot 2023-11-07 at 18 12 00" src="https://github.com/honojs/website/assets/10682/ee169089-d0bf-42f5-ae0f-c652aac59d35">

**Comment by sor4chi** [comment]
> We must ensure they do not duplicate the content of the Guides or API pages.
Yes, it is. 

Maybe you should re-list what you want to write based on the list above and @yusukebe 's thought.

Hono Storage is still unstable and we would like to add it to document at the time of a minor release.

Speaking of ecosystems, how about adding Remix Hono?
I like his project very much.
