### ISSUE TITLE
Add documentation for JWT based utilities

### ISSUE THREAD

**Issue by justinnoel** [honojs/website#21]
Developers can create and verify their own JWTs using Hono Jwt utilities. However, this is not documented.

I'd be happy to add this documentation. I'd suggest adding it as follows:

- API
  - Utilities
    - JWT
      - encode
      - decode
      - verify

Please let me know if you'd like me to proceed and confirm where you'd want this in the docs.

**Comment by ThatOneBro** [comment]
Cool, sounds like a good idea. If you want to go ahead and write it, feel free! Otherwise I can add it this weekend.

**Comment by yusukebe** [comment]
Hi @justinnoel @ThatOneBro 

I thought about that for a night.

Utilities that are put in [src/utils](https://github.com/honojs/hono/tree/main/src/utils) were created for internal use. It is possible that breaking changes or renaming may be made without an announcement. If we document it, we are likely to change it more often or forget about it.

So I suggest that we write the following.

* Using the utilities is OK but may be changed without announcement.
* List of examples of utilities.
* Refer to [src/utils](https://github.com/honojs/hono/tree/main/src/utils).

**Comment by ThatOneBro** [comment]
I think that makes sense. Later maybe we can create an "external utils" path, and wrap the internal methods. Then would provide external utils with a stable API while still allowing the internal implementation to change. But this may be best if we wait to do that until a later time. What do you think?

**Comment by yusukebe** [comment]
> Later maybe we can create an "external utils" path, and wrap the internal methods. Then we would provide external utils with a stable API while still allowing the internal implementation to change. 

Oh, I see! I don't know if we will do it or not, but it is a good idea.

> But this may be best if we wait to do that until a later time.

Yes, I think so, it's not time to do it yet.

**Comment by NicoPlyley** [comment]
@yusukebe This can be closed
Solved by #102
