### ISSUE TITLE
Broken link for "Building a larger application" in RPC guide

### ISSUE THREAD

**Issue by rexfordessilfie** [honojs/website#237]
# Problem
The link for "Building a larger application" in the RPC section of the docs should point to the **"Building a larger application"** section on the **"Best Practices"** page, but points to a section/fragment on the "RPC" guide that does not exist!

Relevant Link: https://hono.dev/guides/rpc#using-with-larger-applications

### Screenshot
<img width="1261" alt="Screenshot 2024-02-10 at 16 16 13" src="https://github.com/honojs/website/assets/43508242/81528e5e-b74c-4d8c-9ccd-bfea2924edb5">

# Solution
I think this can be fixed by updating the link in the docs [here](https://github.com/honojs/website/blob/b05b6dc9ef37194a6488c2e5c835580529577c90/guides/rpc.md?plain=1#L247) to point to `/guides/best-practices#building-a-larger-application`.

Happy to make this quick fix or let someone else handle! Thanks for the awesome docs!

**Comment by yusukebe** [comment]
Hi @rexfordessilfie 

It should be fixed, and the solution is good! Could you create a PR?

**Comment by rexfordessilfie** [comment]
> Hi @rexfordessilfie 
> 
> 
> 
> It should be fixed, and the solution is good! Could you create a PR?

Definitely @yusukebe! PR coming right up!

**Comment by rexfordessilfie** [comment]
PR opened here, @yusukebe: https://github.com/honojs/website/pull/238 👍
