### ISSUE TITLE
Specify the extension of the file that uses jsx with jsx.

### ISSUE THREAD

**Issue by k35o** [honojs/website#241]
The syntax highlighting for the parts that use JSX was ts and js.
We believe these should be corrected to jsx or tsx, but what do you think?
The relevant parts are as follows.

- js
  - https://github.com/honojs/website/blob/main/middleware/builtin/jsx-renderer.md#usage
- ts
  - https://github.com/honojs/website/blob/main/api/context.md#render--setrenderer
  - https://github.com/honojs/website/blob/main/guides/rpc.md#using-swr
  - https://github.com/honojs/website/blob/main/helpers/html.md#insert-snippets-into-jsx
  - https://github.com/honojs/website/blob/main/helpers/ssg.md#manual

## ref
https://hono.dev/api/context#render-setrenderer
<img width="717" alt="スクリーンショット 2024-02-14 16 36 41" src="https://github.com/honojs/website/assets/81804171/67b40a68-cc4c-45d0-bd30-2941324074a4">

**Comment by k35o** [comment]
thanks.@yusukebe 

It would be nice to use `tsx` or `jsx`.
I'd like to fix the documentation as well, if not intentional, since the syntax highlighting is a bit broken.

**Comment by yusukebe** [comment]
@k35o 

> I'd like to fix the documentation as well, if not intentional, since the syntax highlighting is a bit broken.

Pleeeeease! We welcome your PR!

**Comment by k35o** [comment]
@yusukebe 
Thank you!!!
Open it.

https://github.com/honojs/website/pull/242
