### ISSUE TITLE
Service worker documentation and example

### ISSUE THREAD

**Issue by mfulton26** [honojs/website#291]
From what I can tell, Hono can be used for an offline web app in a service worker (even hosted from a web server that only serves static assets).

Can that get officially documented and demonstrated through an example?

I found [this](https://github.com/yusukebe/service-worker-magic), which is magical indeed, but I think a simpler example that doesn't use the same service worker between Cloudflare and browser but a simple browser example would be sufficient and beneficial (your magical example could be linked to it included too).

I think officially documenting on the site and linking to a Hono example in the example repo with other examples would help demonstrate that Hono really can be ran in most any JS runtime and that it can be used to power an offline only web app (installed while online but then requires no Internet connection for usage).

**Comment by yusukebe** [comment]
Hi @mfulton26 

Great idea! I know some users use Hono inside a service worker in production. So it's not only for magic. I'd like to have it.

**Comment by mfulton26** [comment]
I'm starting to look at Honox too. I'd love to bundle Next.js / Remix / Deno Fresh like app routing into a service worker. If Honox targets multiple different JS runtimes like Hono (which I'm guessing it will as it appears to be built on top of Hono) then large, multi-route apps can be served from the edge and from service workers with high code reuse. Sounds amazing to me!

**Comment by yusukebe** [comment]
Now, we have Service Worker Adapter and the document on our website:

https://hono.dev/docs/getting-started/service-worker

We can close this issue!
