### ISSUE TITLE
"How to write your middleware"

### ISSUE THREAD

**Issue by yusukebe** [honojs/website#317]
We have to write "How to write your middleware".

* This should include how to override the response after `next`: https://github.com/honojs/hono/issues/960#issuecomment-2078955638
* Recommend use the `createMiddleware()` method.

**Comment by NicoPlyley** [comment]
Where do you want this placed on the website? Is this for snippets or part of the main docs?

**Comment by yusukebe** [comment]
@NicoPlyley 

Hi Nico.

> Is this for snippets or part of the main docs?

The main docs. I think "[/guides/middleware](https://hono.dev/guides/middleware)" will be best.
