### ISSUE TITLE
Hono on Azure Functions

### ISSUE THREAD

**Issue by Marplex** [honojs/website#346]
Hey everyone! I [made an adapter](https://github.com/Marplex/hono-azurefunc-adapter) for Azure Functions. 
I think it would be great to add an "Azure Functions" page to the Getting Started section.

I noticed that most of the adapters/middlewares/helpers are from the official "hono" account.
Would you allow for my library to be part of the docs, or is there another way we could do this?  @yusukebe 

Thanks!

**Comment by yusukebe** [comment]
> Hey everyone! I [made an adapter](https://github.com/Marplex/hono-azurefunc-adapter) for Azure Functions. 

Awesome! This was requested in https://github.com/honojs/hono/issues/1747

cc: @gunta @ytnobody

> Would you allow for my library to be part of the docs, or is there another way we could do this?

Though it's difficult making an "Azure Functions" starter template for the [create-hono](https://github.com/honojs/create-hono), I think you can put the instruction using your library on the "Getting Started" like the following:

![CleanShot 2024-05-09 at 14 44 14@2x](https://github.com/honojs/website/assets/10682/b2e53b1c-5e6f-4d56-9b0a-a9cc9adce64f)

If you create the PR, we'll review it for merging.

**Comment by ytnobody** [comment]
Awesome! 👏

**Comment by Marplex** [comment]
I made a PR for the getting started guide. The setup is pretty easy when using the azure functions cli. I don't know if it's worth creating and maintaining an azure functions starter template 🤔

**Comment by yusukebe** [comment]
@Marplex 

Thanks! I'll see it later.

> I don't know if it's worth creating and maintaining an azure functions starter template 🤔

I think it's necessary!

**Comment by Marplex** [comment]
> I think it's necessary!

Ok, I would like to work on this

**Comment by yusukebe** [comment]
@Marplex 

ahhhhhhh. Sorry. I wanted to say "I think it's **not** necessary!". So, you don't have to create it!

**Comment by NicoPlyley** [comment]
@yusukebe closed #348

**Comment by gunta** [comment]
Amazing!
