### ISSUE TITLE
Documentation strict mode false statement

### ISSUE THREAD

**Issue by Fecony** [honojs/website#37]
Documentation mentions that strict mode is set to `false` by default -> https://hono.dev/api/hono#strict-mode
But it is not https://github.com/honojs/hono/blob/main/src/hono.ts#L61

Documentation should be changed or strict mode set to false?

**Comment by yusukebe** [comment]
Hi @Fecony !

Thanks for pointing it out.

The default value of `strict` is `true`. "The documentation is wrong". So, documentation should be changed.

**Comment by yusukebe** [comment]
@Fecony 

Fixed! https://hono.dev/api/hono#strict-mode

Thanks!
