### ISSUE TITLE
Add `honojs` install script on an existing project

### ISSUE THREAD

**Issue by PlayerNguyen** [honojs/website#377]
## Current state
By visiting Get Started > Bun, I did not see any command (script) to install from an existing project.

## Expected state
Split [this ](https://github.com/honojs/website/blob/main/getting-started/bun.md) site (Section **2. Setup**) into 2 parts, the first part presents a new project by using bun creat project by using `bun create hono my-app`. The second part presents using `bun install ...`.

## Screenshot
![Screenshot 2024-06-01 104147](https://github.com/honojs/website/assets/10703461/5e56baf3-426d-4da1-9354-22737f0b9601)
_I have a folder already, just need to `bun install hono..` instead_

**Comment by PlayerNguyen** [comment]
I already finished it, check out [this ](https://github.com/honojs/website/pull/378)PR.

**Comment by yusukebe** [comment]
@PlayerNguyen Can we close this?
