### ISSUE TITLE
Cloudflare Pages setup without CLI

### ISSUE THREAD

**Issue by NicoPlyley** [honojs/website#407]
Someone in the Discord was having issues setting up Cloudflare Pages on Cloudflare's website. They did not know which framework to select and output-dir. It was their first time using CF Pages and Hono. 

Since on pages, you can use a GUI to link your code from a Git repository, I think it would be helpful to add an example to CF Pages getting started guide directly, the examples section (with a link in getting started), or link documentation from Cloudflare on setting this up.

Let me know what you think and which option, if any, and I would be happy to add it.

**Comment by yusukebe** [comment]
> Since on pages, you can use a GUI to link your code from a Git repository, I think it would be helpful to add an example to CF Pages getting started guide directly, the examples section (with a link in getting started), or link documentation from Cloudflare on setting this up.

Ahhh, this means running **Hono app** on Cloudflare Pages with setting **GUI/GitHub integration**?  honestly, I've never tried it. But mentioning the GUI is a good thing. And we can describe it.

Btw, we/I have to update the tutorial on the official Cloudflare docs, but I have not worked on it yet:

https://developers.cloudflare.com/pages/framework-guides/deploy-a-hono-site/

Related to: https://github.com/honojs/hono/issues/838

**Comment by NicoPlyley** [comment]
Yes, this would be the GUI/GitHub integration. I usually do my CF Pages this way because it allows for seamless CI/CD. Do you think this should go in `/docs/getting-started/cloudflare-pages`? Or linked in an example?

> Btw, we/I have to update the tutorial on the official Cloudflare docs, but I have not worked on it yet:

I'd be happy to look at this and update it accordingly.

**Comment by yusukebe** [comment]
> Yes, this would be the GUI/GitHub integration. I usually do my CF Pages this way because it allows for seamless CI/CD. Do you think this should go in `/docs/getting-started/cloudflare-pages`? Or linked in an example?

I think `/docs/getting-started/cloudflare-pages` is the best place!
