### ISSUE TITLE
IP restrictions middleware options is empty

### ISSUE THREAD

**Issue by ryuapp** [honojs/website#449]
https://hono.dev/docs/middleware/builtin/ip-restriction#options
![image](https://github.com/user-attachments/assets/26117b30-4bc0-4e3a-934f-626b94094e23)

**Comment by ryuapp** [comment]
This middleware did not have any options :D
https://github.com/honojs/hono/blob/main/src/middleware/ip-restriction/index.ts

**Comment by yusukebe** [comment]
@ryuapp 

Ah, I think we can remove the option section for IP Restriction Middleware. What do you think of it?

**Comment by ryuapp** [comment]
The section should be removed. And, it will be removed in #429.

**Comment by yusukebe** [comment]
@ryuapp Thanks!
