### ISSUE TITLE
Cloudflare workers no longer support jest-environment-miniflare, or vitest-environment-miniflare 

### ISSUE THREAD

**Issue by JagritGumber** [honojs/website#465]
According to the documentation for workers 3 [as per over here](https://developers.cloudflare.com/workers/testing/vitest-integration/get-started/migrate-from-miniflare-2/), Cloudflare docs recommend to update to `@cloudflare/vitest-pool-workers` and the link also has a migration guide to it, The hono docs doesn't seem to be updated about that they still recommend the old method which is kind of misleading.

Would be happy to fix it if too busy.

**Comment by yusukebe** [comment]
@JagritGumber 

You are right! It's outdated. Can you update the docs?

**Comment by JagritGumber** [comment]
Yup Sure, Should I just change the line or add the example project too as I came across this and feel like it is really helpful https://github.com/yusukebe/testing-d1-app-with-types

**Comment by yusukebe** [comment]
@JagritGumber 

Adding some lines is OK.

But, examples like my project will also be useful. How about adding the example on https://hono.dev/examples/ ?

**Comment by JagritGumber** [comment]
@yusukebe That is a good idea because It isn't currently in the examples but sure is a really good example using drizzle and the testing library. I think I could add it to the examples.

**Comment by JagritGumber** [comment]
#487 pull request has been created regarding this issue.

**Comment by yusukebe** [comment]
This is closed by #487. Thanks!
