### ISSUE TITLE
fix: improve the useRequestContext example

### ISSUE THREAD

**Issue by MathurAditya724** [honojs/website#513]
With the current example shown here - https://hono.dev/docs/middleware/builtin/jsx-renderer#userequestcontext we are not showing the use of `RequestContext` needs to be applied. Here is a full working example -

```ts
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { useRequestContext, RequestContext } from "hono/jsx-renderer";

const app = new Hono();

const Component = () => {
  const c = useRequestContext();
  return <b>{c.req.url}</b>;
};

app.get("/", (c) => {
  return c.render(
    <RequestContext value={c}>
      <Component />
    </RequestContext>
  );
});

const port = 3001;
console.log(`Server is running on port ${port}`);

serve({
  fetch: app.fetch,
  port,
});
```
This is for the `nodejs` runtime. I can update the docs and create a PR for this.

**Comment by yusukebe** [comment]
Hi @MathurAditya724 

It's not cleared exactly, but I intended to use `useRequestContext` with `jsxRenderer`. So, if you use it, `RequestContext` is not needed.

```ts
import { useRequestContext, jsxRenderer } from 'hono/jsx-renderer'

const app = new Hono()

app.use(jsxRenderer()) // <---
```

We should discuss it, but originally, `useRequestContext` was created for JSX Renderer, and using JSX Renderer means you don't have to import and use `RequestContext` directly, like the above example.

**Comment by MathurAditya724** [comment]
Interesting I think we should add this one-liner then `app.use(jsxRenderer())` in the example as it will make it clearer.
