### ISSUE TITLE
Request for clarity on "Return HTML" docs

### ISSUE THREAD

**Issue by BrianDouglasIE** [honojs/website#519]
In the "Getting Started" docs under the "Return HTML" section. There is a line that reads:

> Hono is also suitable for returning **a little** HTML.

I've highlighted the **a little** descriptor. Could some explanation be added for why **a little** is used. It poses more questions than perhaps is intended. Such as:

 - What is too much HTML?
 - How much is a little?
 - Should Hono not be used if the app is entirely ssr html?

https://hono.dev/docs/getting-started/basic#return-html

https://github.com/honojs/website/blob/cbb25dc332b18cb70bf985c28a3cef627e99b454/docs/getting-started/basic.md?plain=1#L177

**Comment by yusukebe** [comment]
Hi @BrianDouglasIE 

Thank you for the issue. It was bad. I've fixed it with #520.
