### ISSUE TITLE
Improve documents for Built-in middleware

### ISSUE THREAD

**Issue by yusukebe** [honojs/website#6]
Currently, documents for Built-in middleware are incomplete. The explanation is too simple, and no description of "*options*".

I've written the page for Pretty JSON Middleware: <https://honojs.dev/docs/builtin-middleware/pretty-json/>

We will complete the other middleware pages using this as a reference.

- [x] Basic Authentication
- [x] Bearer Authentication
- [x] Cache
- [x] Compress
- [x] CORS
- [x] ETag
- [x] html => https://hono.dev/helpers/html
- [x] JSX => https://hono.dev/guides/jsx
- [x] JWT Authentication
- [x] Logger
- [x] Pretty JSON
- [x] Validator

**Comment by ThatOneBro** [comment]
@yusukebe Great, thanks for creating this list! I'll start working on it later today.

**Comment by ThatOneBro** [comment]
I'll finally be working on the documentation this weekend 😄  I thought I would have more time this week but work kept me up many late nights this week 😅 But I can't wait to work on Hono docs this weekend 🔥

**Comment by NicoPlyley** [comment]
@yusukebe Can you update this list of what stills needs to be done

**Comment by yusukebe** [comment]
@NicoPlyley Okay, I'll do it later.

**Comment by yusukebe** [comment]
Hi @NicoPlyley 

I just checked and I think all the middleware documentation is sufficient.

So, I'll close this issue. Thanks @ThatOneBro and @NicoPlyley !
